"""initial migration

Revision ID: ace808053d85
Revises: 
Create Date: 2025-02-22 15:40:31.154519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ace808053d85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelai_ledger_entries',
    sa.Column('operation', sa.Enum('DAILY_REWARD', 'SIGNUP_CREDIT', 'CREDIT_SPEND', 'CREDIT_ADD', 'CONTENT_CREATION', 'CONTENT_ACCESS', name='travelailedgeroperation'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce'),
    schema='travelai'
    )
    op.create_index(op.f('ix_travelai_travelai_ledger_entries_id'), 'travelai_ledger_entries', ['id'], unique=False, schema='travelai')
    op.drop_table('alembic_version', schema='healthai')
    op.drop_index('ix_healthai_healthai_ledger_entries_id', table_name='healthai_ledger_entries', schema='healthai')
    op.drop_table('healthai_ledger_entries', schema='healthai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthai_ledger_entries',
    sa.Column('operation', postgresql.ENUM('DAILY_REWARD', 'SIGNUP_CREDIT', 'CREDIT_SPEND', 'CREDIT_ADD', 'CONTENT_CREATION', 'CONTENT_ACCESS', name='healthailedgeroperation'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nonce', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='healthai_ledger_entries_pkey'),
    sa.UniqueConstraint('nonce', name='healthai_ledger_entries_nonce_key'),
    schema='healthai'
    )
    op.create_index('ix_healthai_healthai_ledger_entries_id', 'healthai_ledger_entries', ['id'], unique=False, schema='healthai')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    schema='healthai'
    )
    op.drop_index(op.f('ix_travelai_travelai_ledger_entries_id'), table_name='travelai_ledger_entries', schema='travelai')
    op.drop_table('travelai_ledger_entries', schema='travelai')
    # ### end Alembic commands ###
