"""create healthai ledger model

Revision ID: a69361f70751
Revises: 
Create Date: 2025-02-23 04:55:44.295552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69361f70751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthai_ledger_entries',
    sa.Column('operation', sa.Enum('DAILY_REWARD', 'SIGNUP_CREDIT', 'CREDIT_SPEND', 'CREDIT_ADD', 'CONTENT_ACCESS', 'CONTENT_CREATION', name='healthailedgeroperation'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce'),
    schema='healthai'
    )
    op.create_index(op.f('ix_healthai_healthai_ledger_entries_id'), 'healthai_ledger_entries', ['id'], unique=False, schema='healthai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthai_healthai_ledger_entries_id'), table_name='healthai_ledger_entries', schema='healthai')
    op.drop_table('healthai_ledger_entries', schema='healthai')
    # ### end Alembic commands ###
